name: flutter_local_notifications
description: A Flutter plugin for displaying local notifications on Android and iOS.
version: 16.3.3
homepage: https://github.com/MaikuB/flutter_local_notifications

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^7.2.0
  flutter_plugin_android_lifecycle: ^2.0.27
  timezone: ^0.9.2
  platform: ^3.1.0
  intl: ^0.18.1

flutter:
  plugin:
    platforms:
      android:
        package: com.dexterous.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin 